###
GET http://localhost:5000/rooms/all


###
POST http://localhost:5000/rooms/create
Content-Type: application/json

{
     "roomId": "r8",
    "seatsAvailable": "5",
    "amenities": "tv,ac,bed",
    "pricePerhr": "1100"
}

###
POST  http://localhost:5000/booking/create/r4
Content-Type: application/json

{
   "roomId": "r10",
   "seatsAvailable": "55",
   "amenities": "tv,ac,bed",
   "pricePerhr": "1100"
  
     }

###
GET http://localhost:5000/viewbooking


###
GET http://localhost:5000/customers


###
GET http://localhost:5000/customer/Sundaravel

###
GET https://hallbookingapi-s91l.onrender.com/customer/Sundaravel